### ISSUE TITLE
Question on the 1-second length of clip

### ISSUE THREAD

**Issue by SCZwangxiao** [jayleicn/ClipBERT#51]
The length of the clip seems to be a very important hyper-parameters. Have you performed any experiments on it?

When you increase the length, the method degenerates into dense sampling. When you decrease it, the clip may be less informative.

**Comment by jayleicn** [comment]
Hi @SCZwangxiao, we did not perform careful experiments on this hyper-parameter, but simply set it to be 1-sec, mostly because that many video-language datasets have short videos. In our new work, [Revealing Single Frame Bias for Video-and-Language Learning](https://arxiv.org/abs/2206.03428), we explored using only a single sampled frame from the whole video for training, you might be interested in reading it.
